[pytest]
testpaths = tests
addopts = -v --html=reports/reporte.html --self-contained-html
markers =
    ui: pruebas de interfaz web con Selenium
    api: pruebas de API con Requests
    smoke: pruebas criticas de validacion rapida
    regression: pruebas de regresion funcional
    login: pruebas de autenticacion
    catalog: pruebas del catalogo de productos
    cart: pruebas del carrito de compras
    checkout: pruebas del proceso de compra
